sonar.projectKey=mi-proyecto-frontend
sonar.projectName=mi-proyecto-frontend
sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/environments/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.sourceEncoding=UTF-8
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S1874
sonar.issue.ignore.multicriteria.e1.resourceKey=**/app.config.ts
